---
title: "ECCA Sampling"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(dplyr)
library(units)
library(lwgeom)
library(stringr)
```

# Segment Generation

## Functions

```{r}
add_mileposts_to_segment <- function (data) {
  data_segments <- st_cast(data, 'LINESTRING')
  lengths <- as.numeric(st_length(st_transform(data_segments, 2927)) / 5280)
  mp.starts <- c(0, head(lengths, -1))
  mp.ends <- mp.starts + lengths
  data_segments |> mutate(BARM = mp.starts, EARM = mp.ends)
}

extract_milepost_segments <- function (data, start_mp, end_mp) {
  filtered_data <- data |> filter(BARM < {{ end_mp }} & EARM > {{ start_mp }})
  
  clipped_list <- lapply(1:nrow(filtered_data), function(i) {
    chunk_by_mileposts(filtered_data[i, ], start_mp, end_mp)
  })
  
  area <- st_as_sf(data.frame(geometry = do.call(c, clipped_list)), crs = st_crs(data)) |>
    st_transform(2927)
  
  if (nrow(area) > 1) {
    area <- st_line_merge(st_union(area))
  }
  area
}

chunk_by_mileposts <- function (row, start_mp, end_mp) {
  row_start <- row$BARM # beginning of accumulated range of mileage
  row_end <- row$EARM # ending of accumulated range of mileage
  row_length <- row_end - row_start
  
  if (row_start >= end_mp || row_end < start_mp) {
    return (NULL)
  }
  
  new_start <- max(row_start, start_mp)
  new_end <- min(row_end, end_mp)
  
  if (new_start >= new_end) {
    return (NULL)
  }
  
  t_start <- (new_start - row_start) / row_length
  t_end <- (new_end - row_start) / row_length
  st_linesubstring(row$geometry, t_start, t_end)
}

create_segments <- function (area, segment_length=10^10) {
  line <- area[1,]
  line_length <- as.numeric(st_length(line))

  fractions <- fixed_length_fractions(line_length, segment_length)
  n_segments <- nrow(fractions)
  
  lapply(seq_len(n_segments), function(i) {
    st_linesubstring(line, from = fractions$starts[i], to = fractions$ends[i])
  }) |>
    data.frame() |>
    t() |>
    st_sfc() |>
    st_as_sf(crs = st_crs(line))
}

# this forces all segments the same length and distributes the remaining gap as equal-sized chunks between all the real segments
fixed_length_fractions <- function (line_length, segment_length) {
  total_gap <- line_length %% segment_length
  n_segments <- floor(line_length / segment_length)
  gap_step <- total_gap / (n_segments - 1)
  step_size = segment_length + gap_step
  
  segment_starts <- seq(0, line_length, by=step_size)
  segment_ends <- pmin(segment_starts + segment_length, line_length)
  
  fraction_starts <- segment_starts / line_length
  fraction_ends <- segment_ends / line_length
  data.frame(starts=fraction_starts, ends=fraction_ends)
}

make_data_frame <- function (segments, start_mp, end_mp, area_label, segment_prefix=NULL) {
  segments$area <- area_label
  segments$area.id <- str_c(segment_prefix, seq_len(nrow(segments)), sep='-')
  
  mp_seq <- seq(start_mp, end_mp, length.out = nrow(segments) + 1)
  segments$start.milepost <- head(mp_seq, -1)
  segments$end.milepost   <- tail(mp_seq, -1)
  
  segments <- st_transform(segments, 4326) # lat/long coordinates
  start_points <- st_startpoint(segments) |> st_coordinates()
  segments$start.latitude <- as.character(start_points[,1])
  segments$start.longitude <- as.character(start_points[,2])
  segments$start.maplink <- paste0("https://www.google.com/maps?q=", segments$start.lon, ",", segments$start.lat)
  
  end_points <- st_endpoint(segments) |> st_coordinates()
  segments$end.latitude <- as.character(end_points[,1])
  segments$end.longitude <- as.character(end_points[,2])
  segments$end.maplink <- paste0("https://www.google.com/maps?q=", segments$end.lon, ",", segments$end.lat)

  segments
}
```

## Highway Stretches (Increasing/Decreasing)

The LRS map includes separate segments for increasing mileposts (south side, eastbound) and decreasing mileposts (north side, westbound).

```{r}
make_highway_segments <- function (data, start_mp, end_mp, segment_size, label, area_prefix) {
  extract_milepost_segments(data, start_mp, end_mp) |>
    create_segments(segment_size) |>
    make_data_frame(start_mp, end_mp, label, area_prefix)
}

highway_segment_size = 600 # feet
highway_file <- './data/WSDOT_-_State_Route_Linear_Referencing_System_(LRS)_Current.shp'
routes <- st_read(highway_file)

wa14_mp_inc <- routes |>
  filter(RouteIdent == '014i') |> # Eastbound/south side (mileposts increasing)
  add_mileposts_to_segment()

wa14_mp_dec <- routes |>
  filter(RouteIdent == '014d') |> # Westbound/north side (mileposts decreasing)
  add_mileposts_to_segment()

# Mile post boundaries are based on ECCA agreements with the state
area1N <- make_highway_segments(wa14_mp_dec, 10.0, 11.99, highway_segment_size, 'Highway: Camas-N', 'H1')
area1S <- make_highway_segments(wa14_mp_inc, 10.09, 10.58, highway_segment_size, 'Highway: Camas-S', 'H2')
area2S <- make_highway_segments(wa14_mp_inc, 13.75, 14.3, highway_segment_size, 'Highway: Washougal-SW-Extra', 'H3')
area3N <- make_highway_segments(wa14_mp_dec, 15.05, 17.0, highway_segment_size, 'Highway: Washougal-N', 'H4')
area3S <- make_highway_segments(wa14_mp_inc, 15.05, 17.0, highway_segment_size, 'Highway: Washgoual-S', 'H5')
```

## Ramps

```{r}
make_ramp_segments <- function (data, id, start_mp, end_mp, label) {
  area <- data |> filter(RouteID == id) |>
    add_mileposts_to_segment() |>
    extract_milepost_segments(start_mp, end_mp) |>
    create_segments() |>
    make_data_frame(start_mp, end_mp, label) |>
    mutate(area.id = id)
}

is_on_ramp <- function (ramp) {
  ramp_code <- (ramp$area.id |> strsplit(''))[[1]][4]
  ramp_code == 'Q' | ramp_code == 'S'
}

is_off_ramp <- function (ramp) {
  !is_on_ramp(ramp)
}

ramp_file <- './data/WSDOT_-_State_Route_Ramp_(1%3A24K)_Current.shp'
ramps <- st_read(ramp_file)


vancouver_ramps <- rbind(
  make_ramp_segments(ramps, '014Q101046', 0.01, 0.21, 'Ramp: Vancouver S on-ramp'),
  make_ramp_segments(ramps, '014R101037', 0.06, 0.27, 'Ramp: Vancouver N off-ramp'),
  deparse.level = 1
)

camas_ramps <- rbind(
  make_ramp_segments(ramps, '014S101194', 0.13, 0.34, 'Ramp: Camas N on-ramp'),
  make_ramp_segments(ramps, '014P101203', 0.03, 0.29, 'Ramp: Camas S off-ramp'),
  deparse.level = 1
)

washgoual_on_ramp <- make_ramp_segments(ramps, '014Q101544', 0, 0.26, 'Ramp: Washougal S on-ramp') # eastern pair
washougal_off_ramp <- make_ramp_segments(ramps, '014P101430', 0.07, 0.38, 'Ramp: Washougal S off-ramp') # western pair, part of "unofficial" stretch
washougal_ramps <- rbind(washgoual_on_ramp, washougal_off_ramp, deparse.level = 1)
```

# Sampling

The official sampling has already been run so this shouldn't be needed other than for reference.

```{r}
# These are the officially sampled areas
sample_area_ids = c('H1-8', 'H2-1', 'H3-3', 'H4-10', 'H5-5', '014Q101046', '014S101194', '014P101430')

### Code that was previously used for determining the above sampled areas
#
# sample_area <- function (area, n) {
#   indices <- sample(nrow(area), n)
#   area[indices,]
# }
#
# vancouver_ramp_sample <- sample_area(vancouver_ramps, 1)
# camas_ramp_sample <- sample_area(camas_ramps, 1)
# both_are_on_ramps <- is_on_ramp(vancouver_ramp_sample) & is_on_ramp(camas_ramp_sample)
# both_are_off_ramps <- is_off_ramp(vancouver_ramp_sample) & is_off_ramp(camas_ramp_sample)
#
# washougal_ramp_sample <- NA
#
# if (both_are_off_ramps) {
#   washougal_ramp_sample <- washgoual_on_ramp
# } else if (both_are_on_ramps) {
#   washougal_ramp_sample <- washougal_off_ramp
# } else {
#   washougal_ramp_sample <- sample_area(washougal_ramps, 1)
# }
#
# samples <- rbind(
#   sample_area(area1N, 1),
#   sample_area(area1S, 1),
#   sample_area(area2S, 1),
#   sample_area(area3N, 1),
#   sample_area(area3S, 1),
#   vancouver_ramp_sample,
#   camas_ramp_sample,
#   washougal_ramp_sample,
#   deparse.level = 1
# )
```

# Testing & Verification

```{r}
verify_segment_lengths <- function (area) {
  segment_lengths <- area |> st_transform(2927) |> st_length()
  area_length <- segment_lengths |> sum() / 5280
  c(segment_lengths, area_length)
}

verify_segment_lengths(area1N)
verify_segment_lengths(area1S)
verify_segment_lengths(area2S)
verify_segment_lengths(area3N)
verify_segment_lengths(area3S)

verify_segment_lengths(vancouver_ramps)
verify_segment_lengths(camas_ramps)
verify_segment_lengths(washougal_ramps)
```

# Export

```{r}
out_dir = 'out'
if (!dir.exists(out_dir)) {
  dir.create(out_dir)
}

full_data <- data.frame(rbind(area1N, area1S, area2S, area3N, area3S, vancouver_ramps, camas_ramps, washougal_ramps, deparse.level = 1))
data_cols <- colnames(full_data) |> head(-1) # exclude geometry data in the last column
full_data <- full_data[, data_cols]
write.csv(full_data, paste0(out_dir, '/full.csv'))

sample_data <- full_data |> filter(area.id %in% sample_area_ids)
write.csv(sample_data, paste0(out_dir, '/samples.csv'))
```
